[IEM] Adding a conflict for rman since there is a package for that specific application already.  Also fixing some scripting errors with kdm

diff --git a/debian/kdm.postinst b/debian/kdm.postinst
--- a/debian/kdm.postinst
+++ b/debian/kdm.postinst
@@ -28,21 +28,21 @@ esac
 
 if test "$update" = "yes"; then
 echo "Updating kdmrc ..."
-grep -vE "^(NoUsers|SessionTypes)" /etc/kde/kdmrc > /tmp/kdmrc
-echo "[KDM]" >> /tmp/kdmrc  
-echo -n "NoUsers=" >> /tmp/kdmrc
+TMPFILE=`mktemp /tmp/kdmtemp.XXXXXX` || exit 1
+grep -vE "^(NoUsers|SessionTypes)" /etc/kde/kdmrc > $TMPFILE
+echo -n "NoUsers=" >> $TMPFILE
 for user in `sed -e 's#^\([^:]*\):.*:\([0-9]*\):.*$#\2-\1#' /etc/passwd`; do 
     id=`echo $user | sed -e "s#-.*##"`
     if test -n "$id" && test ! "$id" = "0" && test ! `expr "$id" \< 1000` = "0" || test ! `expr "$id" \> 65500` = "0"; then
-	echo -n "$user;" | sed -e 's#[0-9]*-##' >> /tmp/kdmrc
+	echo -n "$user;" | sed -e 's#[0-9]*-##' >> $TMPFILE
     fi
 done
-echo "" >> /tmp/kdmrc
-echo -n "SessionTypes=kde;" >> /tmp/kdmrc
+echo "" >> $TMPFILE
+echo -n "SessionTypes=default;kde;failsafe;" >> $TMPFILE
 for session in `grep -v "^#" /etc/X11/window-managers | sed -e 's#^.*/\([^/]*\)$#\1#' | sort -u | grep -v kde`; do
-    echo -n "$session;" >> /tmp/kdmrc
+    echo -n "$session;" >> $TMPFILE
 done
-mv /tmp/kdmrc /etc/kde/kdmrc
+mv $TMPFILE /etc/kde/kdmrc
 fi
 
 if ! grep -q "^# Start kdebase added code" /etc/X11/xdm/Xsetup_0; then
