[IEM] This is a cleanup sweep through post/pre scripts.  Found bugs in post/pre scripts for kdm.  These follow deb policy closer and are alot cleaner.  Also removed non used purge and window-managers files.  Updated changelog.  updated depends fields in control file.

diff --git a/debian/kdm.postinst b/debian/kdm.postinst
--- a/debian/kdm.postinst
+++ b/debian/kdm.postinst
@@ -1,45 +1,102 @@
-#!/bin/sh
+#! /bin/sh
+# postinst script for kdm
+#
 # Mostly stolen from the Debian xdm scripts
 # Copyright 1998, 1999 Branden Robinson.  Licensed under the GNU GPL.
 # Acknowlegements to Stephen Early, Mark Eichin, and Manoj Srivastava.
+#
+# see: dh_installdeb(1)
 
 set -e
-
-echo -n "Verifying /var/state/kdm dir: ";
-if test /var/state/kdm; then
-  echo "Exists!";
-else
-  mkdir /var/state/kdm > /dev/null 2>&1
-  echo "Created!";
-fi
-
-echo -n "Verifying kdm links: ";
-if test /usr/X11R6/lib/X11/kdm; then
-  echo -n "...";
-else 
-  mkdir /usr/x11R6/lib/X11/kdm > /dev/null 2>&1
-  echo -n "...";
-fi
-cd /usr/X11R6/lib/X11/kdm 
-rm -f *
-ln -s /etc/X11/kdm/kdm-config xdm-config > /dev/null 2>&1
-ln -s /etc/X11/kdm/* .  > /dev/null 2>&1
-echo "Done!";
-
 
 cleanup () {
   # unroll changes in kdm preinst
   for file in /usr/X11R6/lib/X11/kdm/kdm-config; do
-    if [ -e $file.kdm-old ]; then
-      rm $file
+    if [ -e $file.kdm-old ]; then 
+      rm $file         
       mv $file.kdm-old $file
     fi
   done
-}
+}              
 
-if [ "$1" = "configure" ]; then
-  update-rc.d kdm defaults 99 01 >/dev/null
-fi  
+
+case "$1" in
+    configure)
+      echo -n "Verifying /var/state/kdm dir: ";
+      if test /var/state/kdm; then
+        echo "Exists!";
+      else
+         mkdir /var/state/kdm > /dev/null 2>&1
+         echo "Created!";
+      fi
+      echo -n "Verifying kdm links: ";
+      if test /usr/X11R6/lib/X11/kdm; then
+        echo -n "...";
+      else 
+        mkdir /usr/X11R6/lib/X11/kdm > /dev/null 2>&1
+        echo -n "...";
+      fi
+      cd /usr/X11R6/lib/X11/kdm 
+      rm -f *
+      ln -s /etc/X11/kdm/kdm-config xdm-config > /dev/null 2>&1
+      ln -s /etc/X11/kdm/* .  > /dev/null 2>&1
+      echo "Done!";
+      update-rc.d kdm defaults 99 01 >/dev/null
+
+      echo "Do you want to setup kdm for your system installation?"
+      echo "If you enter y here, /etc/kde/kdmrc will be changed to"
+      echo "only list available users and Windowmanagers."
+      echo -n "Do you want to update the kdmrc? [Yn]"
+      read answer
+      if test -z "$answer"; then
+        answer=y
+      else
+        answer=`echo $answer | cut -c1 | tr '[A-Z]' '[a-z]'`
+      fi
+
+      case $answer in
+          y) update=yes ;;
+          n) update=no;;
+          *) echo "\"$answer\" not understood.  Using default of yes"
+             update=no
+          ;;
+      esac
+
+      if test "$update" = "yes"; then
+        echo "Updating kdmrc ..."
+        TMPFILE=`mktemp /tmp/kdmtemp.XXXXXX` || exit 1
+        grep -vE "^(NoUsers|SessionTypes)" /etc/kde/kdmrc > $TMPFILE
+        echo -n "NoUsers=" >> $TMPFILE
+        for user in `sed -e 's#^\([^:]*\):.*:\([0-9]*\):.*$#\2-\1#' /etc/passwd`; do 
+          id=`echo $user | sed -e "s#-.*##"`
+          if test -n "$id" && test ! "$id" = "0" && test ! `expr "$id" \< 1000` = "0" || test ! `expr "$id" \> 65500` = "0"; then
+	    echo -n "$user;" | sed -e 's#[0-9]*-##' >> $TMPFILE
+          fi
+        done
+        echo "" >> $TMPFILE
+        echo -n "SessionTypes=default;failsafe;" >> $TMPFILE
+        for session in `grep -v "^#" /etc/X11/window-managers | sed -e 's#^.*/\([^/]*\)$#\1#' | sort -u`; do
+          echo -n "$session;" >> $TMPFILE
+        done
+        mv $TMPFILE /etc/kde/kdmrc
+      fi
+    ;;
+    abort-upgrade|abort-remove|abort-deconfigure)
+      cleanup
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 0
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+
+#DEBHELPER#
+#KDEHELPER#
 
 nostart=
 for hostname in "" "localhost" "$(hostname)" "$(hostname -f)"; do
@@ -47,7 +104,6 @@ for hostname in "" "localhost" "$(hostname)" "$(hostname -f)"; do
     nostart=yes
   fi
 done
-
 if start-stop-daemon --stop --quiet --signal 0 --pid /var/run/kdm.pid --exec /usr/bin/kdm; then
   nostart=yes
 fi
@@ -55,48 +111,6 @@ fi
 if ! grep -qs ^restart-on-upgrade /etc/X11/kdm/kdm.options; then
   nostart=yes
 fi
-
-echo "Do you want to setup kdm for your system installation?"
-echo "If you enter y here, /etc/kde/kdmrc will be changed to"
-echo "only list available users and Windowmanagers."
-echo -n "Do you want to update the kdmrc? [Yn]"
-read answer
-if test -z "$answer"; then
-  answer=y
-else
-  answer=`echo $answer | cut -c1 | tr '[A-Z]' '[a-z]'`
-fi
-
-case $answer in
- y) update=yes ;;
- n) update=no;;
- *) echo "\"$answer\" not understood.  Using default of yes"
-   update=no
-   ;;
-esac
-
-if test "$update" = "yes"; then
-echo "Updating kdmrc ..."
-TMPFILE=`mktemp /tmp/kdmtemp.XXXXXX` || exit 1
-grep -vE "^(NoUsers|SessionTypes)" /etc/kde/kdmrc > $TMPFILE
-echo -n "NoUsers=" >> $TMPFILE
-for user in `sed -e 's#^\([^:]*\):.*:\([0-9]*\):.*$#\2-\1#' /etc/passwd`; do 
-    id=`echo $user | sed -e "s#-.*##"`
-    if test -n "$id" && test ! "$id" = "0" && test ! `expr "$id" \< 1000` = "0" || test ! `expr "$id" \> 65500` = "0"; then
-	echo -n "$user;" | sed -e 's#[0-9]*-##' >> $TMPFILE
-    fi
-done
-echo "" >> $TMPFILE
-echo -n "SessionTypes=default;failsafe;" >> $TMPFILE
-for session in `grep -v "^#" /etc/X11/window-managers | sed -e 's#^.*/\([^/]*\)$#\1#' | sort -u`; do
-    echo -n "$session;" >> $TMPFILE
-done
-mv $TMPFILE /etc/kde/kdmrc
-fi
-
-#DEBHELPER#
-#KDEHELPER#
-
 [ "$nostart" ] || /etc/init.d/kdm start || true
 
 
